export { default as axiosClient } from './axios/axiosClient'
export { default as configAxiosReq } from './axios/axios.config'
export { default as addCommas } from './number/fixNumber'
export { default as totalArrayProduct } from './array-product/totalArrayProduct'
export { default as saveLocal } from './service/saveLocal'
export { default as getDataInLocal } from './service/getDataInLocal'